name: call-stack
version: 0.4.0
synopsis: Use GHC call-stacks in a backward compatible way
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: sol/call-stack
category: Data

ghc-options: -Wall

dependencies: base == 4.*

library:
  source-dirs: src
  exposed-modules: Data.CallStack
  when:
    - condition: os(windows)
      dependencies: filepath
      cpp-options: -DWINDOWS

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - filepath
      - nanospec
      - call-stack
